### ISSUE TITLE
Piping from request to json-parse-stream fails because it uses buffers

### ISSUE THREAD

**Issue by wraithan** [chrisdickinson/json-parse-stream#1]
``` javascript

var request = require('request')
  , parse = require('json-parse-stream')
  , url = 'http://portland.craigslist.org/jsonsearch/apa/mlt?useMap=1&srchType=A&maxAsk=1400&bedrooms=2&addTwo=purrr'

request(url)
  .pipe(parse())

// wraithbook:cl cmcdonald$ node index.js
// 
// /Users/cmcdonald/devel/cl/node_modules/json-parse-stream/index.js:250
//     chunk = chunk.split('')
//                   ^
// TypeError: Object [[{"Longitude":-122.455003,"PostingURL":"http://portland.craigslist.org/mlt/apa/3920221038.html","Ask":"1245","Bedrooms":"2","ImageThumb":"http://images.craigslist.org/thumb/3rb3tb3J15L45Ka5H2d77e28be05b2fdd18d2.jpg","PostingID":"3920221038","CategoryID":"1","Latitude":45.504422,"PostingTitle":"Start Your Summer Off Right In This BEAUTIFUL Town Home! Rent NOW!","PostedDate":"1373235256"},{"Longitude":-122.664419,"PostingURL":"http://portland.craigslist.org/mlt/apa/3864922375.html","Ask":"1400","Bedrooms":"2","ImageThumb":"http://images.craigslist.org/thumb/3Ec3tf3Kb5K35sc5q5d6b668ebdd9b96d15da.jpg","PostingID":"3864922375","CategoryID":"1","Latitude":45.533299,"PostingTitle":"TWO units left at Eko-Haus KING","PostedDate":"1373235011"},{"Longitude":-122.664419,"PostingURL":"http://portland.craigslist.org/mlt/apa/3907280269.html","Ask":"1350","Bedrooms":"2","ImageThumb":"http://images.craigslist.org/thumb/3te3G73q75Ld5Hb5Jdd718f02352384771b76.jpg","PostingID":"3907280269","CategoryID":"1","Latitude":45.533299,"PostingTitle":"ONE unit left at Eko-Haus MARTIN","PostedDate":"1373234987"},{"Longitude":-122.7087 has no method 'split'
//     at Stream.write (/Users/cmcdonald/devel/cl/node_modules/json-parse-stream/index.js:250:19)
//     at Stream.stream.write (/Users/cmcdonald/devel/cl/node_modules/json-parse-stream/node_modules/through/index.js:25:11)
//     at Stream.EventEmitter.emit (events.js:95:17)
//     at Stream.stream.write (/Users/cmcdonald/devel/cl/node_modules/json-parse-stream/node_modules/duplex/index.js:68:12)
//     at Request.ondata (stream.js:51:26)
//     at Request.EventEmitter.emit (events.js:95:17)
//     at IncomingMessage.<anonymous> (/Users/cmcdonald/devel/cl/node_modules/request/index.js:833:12)
//     at IncomingMessage.EventEmitter.emit (events.js:95:17)
//     at IncomingMessage.<anonymous> (_stream_readable.js:736:14)
//     at IncomingMessage.EventEmitter.emit (events.js:92:17)
```

It appears that request is dumping buffer objects, not string objects. Perhaps this is the problem.

**Comment by wraithan** [comment]
Yeah, adding a stream that just calls `.toString()` on all the stuff coming from request totally fixes this. Not sure if this is a library bug (maybe it should handle this) or a docs bug (it should be explicit at only accepting strings) or expected and I am just bad at node.

**Comment by wraithan** [comment]
Workaround:

``` javascript
var request = require('request')
  , parse = require('json-parse-stream')
  , through = require('through')

function stringifyBuffer() {
  return through(write)
  function write(data) {
    this.queue(data.toString())
  }
}

request('http://google.com')
  .pipe(stringifyBuffer())
  .pipe(parse())

```

**Comment by phated** [comment]
:+1: on this getting fixed ;)
